go: &go
  build: dev-env
  volumes:
    - .:/go/src/stash0.eng.lancope.local/dev-infrastructure/project-lifecycle
  working_dir: /go/src/stash0.eng.lancope.local/dev-infrastructure/project-lifecycle
  environment:
    - GOOS
    - GOARCH
  entrypoint: /usr/local/go/bin/go

package:
  <<: *go
  entrypoint: /opt/lifecycle/package

## shares the host ssh-agent with the container so that we can provide jenkins ssh-agent for publishing actions
## NOTE: this will only work on a pure linux box
publish:
  <<: *go
  volumes:
    - $SSH_AUTH_SOCK:/opt/ssh-agent
    - .:/go/src/stash0.eng.lancope.local/dev-infrastructure/project-lifecycle
  environment:
    - SSH_AUTH_SOCK=/opt/ssh-agent
    - GIT_BRANCH
  entrypoint: /opt/lifecycle/publish

test:
  <<: *go
  command: ["test", "-v", "./..."]

smoketest:
  build: smoketest
  volumes:
    - .:/opt/project/
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/lc_smoketest:/tmp/lc_smoketest
  environment:
    - COMPOSE_PROJECT_NAME=projectlifecyclesmoketests
    - TMPDIR=/tmp/lc_smoketest
  working_dir: /opt/project
  entrypoint: ["rspec", "--require", "./smoketest/spec_helper.rb", "--format", "documentation"]
  command: ["--pattern", "smoketest/**/*.feature"]
