go: &go
  build: dev-env
  volumes:
    - .:/go/src/github.com/elsy
  working_dir: /go/src/github.com/elsy
  environment:
    - GOOS
    - GOARCH
  entrypoint: /bin/bash
    # /usr/local/go/bin/go

installdependencies:
  <<: *go
  entrypoint: govendor
  command: sync

package:
  <<: *go
  environment:
    - GIT_TAG_NAME
  entrypoint: /opt/lifecycle/package

publish:
  <<: *go
  volumes:
    - $LC_REPO_NETRC:/opt/netrc
    - .:/go/src/stash0.eng.lancope.local/dev-infrastructure/project-lifecycle
  environment:
    - ARTIFACTORY_SERVER
    - ARTIFACTORY_PATH
  entrypoint: /opt/lifecycle/publish

test:
  <<: *go
  entrypoint: /opt/lifecycle/test
  command: "./..."

lint:
  <<: *go
  entrypoint: ["/go/bin/golint"]
  command: "./..."

##############################################
############ Blackbox-Test Env ###############
###############################################

## setup two docker registries for running blackbox-tests for publish command
## See: ./blackbox-test/publish.feature
registry1:
  image: registry:2
  ports:
    - 5000:5000
registry2:
  image: registry:2
  ports:
    - 5001:5000

blackbox-test: &BLACKBOXTEST
  build: blackbox-test
  volumes:
    - .:/opt/project/
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/lc_blackbox-test:/tmp/lc_blackbox-test
  environment:
    - COMPOSE_PROJECT_NAME=projectlifecycleblackbox
    - TMPDIR=/tmp/lc_blackbox-test
  links:
    - registry1
    - registry2
