# Copyright 2016 Cisco Systems, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Use lc mvn template with custom mvn install and custom publish service
mvn:
  image: library/maven:3.3.9
test:
  image: library/maven:3.3.9
package:
  image: library/maven:3.3.9

## relies on pom using the mvn deploy plugin and configuring the target mvn repo
publish:
  image: library/maven:3.3.9
  entrypoint: mvn
  command: ["deploy", "-DskipTests=true", "-Dmaven.main.skip=true", "-Dmaven.test.skip=true", "-Dmaven.install.skip=true"]
clean:
  image: library/maven:3.3.9
